---
  environment: vagrant
  chdir: /var/www/balmainweb/current
  address: 0.0.0.0
  port: 5000
  pid:  /var/www/balmainweb/shared/pids/thin.pid
  rackup:  /var/www/balmainweb/current/config.ru
  log:  /var/www/balmainweb/shared/log/thin.log
  max_conns: 1024
  timeout: 60
  max_persistent_conns: 512
  daemonize: true

